services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5232:5432"
    networks:
      - db
networks:
  db:
    driver: bridge

volumes:
  db: